# Generated by Django 2.2 on 2020-06-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Greenery_App', '0002_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='date_plant',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='upload',
        ),
    ]
