# Generated by Django 2.2 on 2020-06-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Greenery_App', '0003_auto_20200608_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='nickname',
        ),
    ]
